### ISSUE TITLE
The bot crashes if it cannot connect to the Telegram server.

### ISSUE THREAD

**Issue by orenlab** [orenlab/pytelemonbot#1]
502 Bad Gateway in Telebot:

```
2024-02-20 06:10:50,325 (__init__.py:1147 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-02-20 06:10:50,326 (__init__.py:1149 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 92, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 633, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 164, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 191, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-02-20 06:10:50,326 (__init__.py:1153 MainThread) INFO - TeleBot: "Exception occurred. Stopping."
2024-02-20 06:10:50,326 (__init__.py:1189 MainThread) INFO - TeleBot: "Stopped polling."
```

**Comment by orenlab** [comment]
Due to a connectivity issue, the Telebot service always throws an error. Because the bot is run in a Docker container, it simply restarts - with the "--always" flag.
